---@module "lazy"
---@type LazySpec
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "diff",
        "jsdoc",
        "markdown",
        "markdown_inline",
        "query",
        "html",
        "html_tags",
        "javascript",
        "json",
        "lua",
        "luadoc",
        "luap",
        "python",
        "tsx",
        "jsx",
        "xml",
        "vim",
        "vimdoc",
        "typescript",
        "yaml",
        "toml",
        "astro",
        "cmake",
        "cpp",
        "c",
        "css",
        "fish",
        "gitignore",
        "go",
        "http",
        "java",
        "php",
        "rust",
        "scss",
        "sql",
        "graphql",
        "regex",
        "latex",
      },
    },
  },
}
